package masterdata;
import koneksisemua.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

    public class data_barang extends javax.swing.JFrame {
    DefaultTableModel tabmode;
    private javax.swing.JFrame parentFrame;
    
    public data_barang() {
    initComponents();

    tampilData();
    kodeOtomatis();

   
    kd_brng.setEditable(false);

   
    n_brng.setEditable(true);

   
    Jmlh.setEditable(false);
    Jmlh.setText("0");
}
    
    protected void kosong() {
        
    Ktgrbrng.setSelectedIndex(0);
    n_brng.setText("");
    ukuran.setText("");
    warna.setText("");
    Jmlh.setText("0");

    
    n_brng.setEditable(true);

  
    kd_brng.setEditable(false);
    Jmlh.setEditable(false);
}

    protected void tampilData() {
        try (Connection conn = koneksi.getConnection()) {
           Object[] baris = {"Kode Barang", "Kategori Barang", "Nama Barang", "Ukuran", "Warna", "Jumlah"};
        tabmode = new DefaultTableModel(null, baris);
        table.setModel(tabmode);

        String sql = "SELECT * FROM barang";
        Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);

        while (hasil.next()) {
            String[] data = {
                hasil.getString("kd_brng"),
                hasil.getString("Ktgrbrng"), 
                hasil.getString("n_brng"),
                hasil.getString("ukuran"),
                hasil.getString("warna"),
                hasil.getString("Jmlh")      
            };
            tabmode.addRow(data);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal tampil: " + e.getMessage());
    }
    }

    private void kodeOtomatis() {
    try (Connection conn = koneksi.getConnection()) {

        String sql =
            "SELECT MAX(CAST(SUBSTRING(kd_brng, 7) AS UNSIGNED)) AS nomor FROM barang";

        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);

       if (rs.next() && rs.getObject("nomor") != null) {
        int nomor = rs.getInt("nomor") + 1;
        kd_brng.setText(String.format("DTBRNG%02d", nomor));
        } else {
        kd_brng.setText("DTBRNG01");
        }
    } catch (Exception e) {

        JOptionPane.showMessageDialog(
            null,
            "Kode otomatis error : " + e.getMessage()
        );

    }
}
    private boolean bolehEditNamaBarang() {

        try (Connection conn = koneksi.getConnection()) {

            // Cek transaksi masuk
            String sqlMasuk =
                "SELECT COUNT(*) FROM ts_brg_msk WHERE kd_brg=?";

            PreparedStatement psMasuk =
                conn.prepareStatement(sqlMasuk);

            psMasuk.setString(1, kd_brng.getText());

            ResultSet rsMasuk =
                psMasuk.executeQuery();

            rsMasuk.next();

            int masuk = rsMasuk.getInt(1);

            // Cek transaksi keluar
            String sqlKeluar =
                "SELECT COUNT(*) FROM ts_brg_klr WHERE kd_brg=?";

            PreparedStatement psKeluar =
                conn.prepareStatement(sqlKeluar);

            psKeluar.setString(1, kd_brng.getText());

            ResultSet rsKeluar =
                psKeluar.executeQuery();

            rsKeluar.next();

            int keluar = rsKeluar.getInt(1);

            // Kalau belum pernah transaksi
            return (masuk == 0 && keluar == 0);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                null,
                e.getMessage()
            );

            return false;
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        kd_brng = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        n_brng = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ukuran = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        warna = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Jmlh = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Ktgrbrng = new javax.swing.JComboBox<>();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        simpan = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        cari = new javax.swing.JTextField();
        mencari = new javax.swing.JButton();
        RESET = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1354, 1149));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 153, 102));

        jPanel4.setBackground(new java.awt.Color(255, 153, 102));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA BARANG");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1287, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1192, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 204, 153));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kode Barang");

        kd_brng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kd_brngActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kategori Barang");

        n_brng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_brngActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ukuran");

        ukuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ukuranActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Warna");

        warna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warnaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Stok Barang");

        Jmlh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmlhActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nama Barang");

        Ktgrbrng.setBackground(new java.awt.Color(255, 153, 51));
        Ktgrbrng.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        Ktgrbrng.setForeground(new java.awt.Color(255, 255, 255));
        Ktgrbrng.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pakaian Atas", "Pakaian Bawah", "Aksesoris", " " }));
        Ktgrbrng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KtgrbrngActionPerformed(evt);
            }
        });

        table.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 51)));
        table.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Kategori Barang", "Nama Barang", "Ukuran", "Warna", "Jumlah "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.setGridColor(new java.awt.Color(255, 255, 255));
        table.setSelectionBackground(new java.awt.Color(0, 153, 255));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        simpan.setBackground(new java.awt.Color(0, 102, 102));
        simpan.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        simpan.setForeground(new java.awt.Color(255, 255, 255));
        simpan.setText("SIMPAN");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        ubah.setBackground(new java.awt.Color(0, 102, 102));
        ubah.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        ubah.setForeground(new java.awt.Color(255, 255, 255));
        ubah.setText("UBAH");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        hapus.setBackground(new java.awt.Color(0, 102, 102));
        hapus.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        hapus.setForeground(new java.awt.Color(255, 255, 255));
        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        mencari.setBackground(new java.awt.Color(0, 102, 102));
        mencari.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        mencari.setForeground(new java.awt.Color(255, 255, 255));
        mencari.setText("CARI");
        mencari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mencariActionPerformed(evt);
            }
        });

        RESET.setBackground(new java.awt.Color(0, 102, 102));
        RESET.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        RESET.setForeground(new java.awt.Color(255, 255, 255));
        RESET.setText("RESET");
        RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ukuran)
                        .addComponent(warna)
                        .addComponent(Jmlh, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Ktgrbrng, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kd_brng, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n_brng, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1094, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(mencari, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RESET, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(kd_brng, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ktgrbrng, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(n_brng, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(ukuran, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warna, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jmlh, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 643, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mencari))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ubah)
                    .addComponent(simpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapus)
                    .addComponent(RESET))
                .addGap(954, 954, 954))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 305, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1047, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kd_brngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kd_brngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kd_brngActionPerformed

    private void n_brngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_brngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n_brngActionPerformed

    private void ukuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ukuranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ukuranActionPerformed

    private void warnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warnaActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
      try (Connection conn = koneksi.getConnection()) {

       
        if (n_brng.getText().trim().isEmpty()
                || ukuran.getText().trim().isEmpty()
                || warna.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(
                null,
                "Nama Barang, Ukuran, dan Warna wajib diisi!"
            );
            return;
        }

        String sql =
            "INSERT INTO barang " +
            "(kd_brng, Ktgrbrng, n_brng, ukuran, warna, Jmlh, hg_beli, hg_jual) " +
            "VALUES (?,?,?,?,?,?,?,?)";

        PreparedStatement ps = conn.prepareStatement(sql);

        ps.setString(1, kd_brng.getText().trim());
        ps.setString(2, Ktgrbrng.getSelectedItem().toString());
        ps.setString(3, n_brng.getText().trim());
        ps.setString(4, ukuran.getText().trim());
        ps.setString(5, warna.getText().trim());

        // Stok awal dan harga awal
        ps.setInt(6, 0);
        ps.setInt(7, 0);
        ps.setInt(8, 0);

        ps.executeUpdate();

        JOptionPane.showMessageDialog(null, "Data berhasil disimpan");

        tampilData();
        kosong();
        kodeOtomatis();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
            null,
            "Gagal menyimpan data : " + e.getMessage()
        );

    }
    
    }//GEN-LAST:event_simpanActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
  try (Connection conn = koneksi.getConnection()) {

        if (bolehEditNamaBarang()) {

        
            String sql =
                "UPDATE barang SET " +
                "Ktgrbrng=?, " +
                "n_brng=?, " +
                "ukuran=?, " +
                "warna=? " +
                "WHERE kd_brng=?";

            PreparedStatement ps = conn.prepareStatement(sql);

            ps.setString(1, Ktgrbrng.getSelectedItem().toString());
            ps.setString(2, n_brng.getText());
            ps.setString(3, ukuran.getText());
            ps.setString(4, warna.getText());
            ps.setString(5, kd_brng.getText());

            ps.executeUpdate();

        } else {

          
            String sql =
                "UPDATE barang SET " +
                "Ktgrbrng=?, " +
                "ukuran=?, " +
                "warna=? " +
                "WHERE kd_brng=?";

            PreparedStatement ps = conn.prepareStatement(sql);

            ps.setString(1, Ktgrbrng.getSelectedItem().toString());
            ps.setString(2, ukuran.getText());
            ps.setString(3, warna.getText());
            ps.setString(4, kd_brng.getText());

            ps.executeUpdate();
        }

        JOptionPane.showMessageDialog(null, "Data berhasil diubah");

        tampilData();
        kosong();
        kodeOtomatis();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Edit Gagal : " + e.getMessage());
    }
    }//GEN-LAST:event_ubahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
  
    try (Connection conn = koneksi.getConnection()) {

        // Cek transaksi barang masuk
        String cekMasuk =
            "SELECT COUNT(*) FROM ts_brg_msk WHERE kd_brg = ?";

        PreparedStatement psMasuk =
            conn.prepareStatement(cekMasuk);

        psMasuk.setString(1, kd_brng.getText());

        ResultSet rsMasuk =
            psMasuk.executeQuery();

        rsMasuk.next();

        int jmlMasuk =
            rsMasuk.getInt(1);

        // Cek transaksi barang keluar
        String cekKeluar =
            "SELECT COUNT(*) FROM ts_brg_klr WHERE kd_brg = ?";

        PreparedStatement psKeluar =
            conn.prepareStatement(cekKeluar);

        psKeluar.setString(1, kd_brng.getText());

        ResultSet rsKeluar =
            psKeluar.executeQuery();

        rsKeluar.next();

        int jmlKeluar =
            rsKeluar.getInt(1);

        // Kalau pernah dipakai transaksi
        if (jmlMasuk > 0 || jmlKeluar > 0) {

            JOptionPane.showMessageDialog(
                null,
                "Barang sudah memiliki transaksi.\nTidak bisa dihapus!"
            );

            return;
        }

        // Baru hapus
        String sql =
            "DELETE FROM barang WHERE kd_brng=?";

        PreparedStatement ps =
            conn.prepareStatement(sql);

        ps.setString(1, kd_brng.getText());

        ps.executeUpdate();

        JOptionPane.showMessageDialog(
            null,
            "Data berhasil dihapus"
        );

        tampilData();
        kosong();
        kodeOtomatis();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
            null,
            e.getMessage()
        );

    }
    }//GEN-LAST:event_hapusActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
   int bar = table.getSelectedRow();

    kd_brng.setText(tabmode.getValueAt(bar, 0).toString());
    Ktgrbrng.setSelectedItem(tabmode.getValueAt(bar, 1).toString());
    n_brng.setText(tabmode.getValueAt(bar, 2).toString());
    ukuran.setText(tabmode.getValueAt(bar, 3).toString());
    warna.setText(tabmode.getValueAt(bar, 4).toString());
    Jmlh.setText(tabmode.getValueAt(bar, 5).toString());
    kd_brng.setEditable(false);
    Jmlh.setEditable(false);

        if (bolehEditNamaBarang()) {
    n_brng.setEditable(true);   
        } else {
    n_brng.setEditable(false);  
        }
    }//GEN-LAST:event_tableMouseClicked

    private void mencariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mencariActionPerformed
     
    String cariData = cari.getText().toLowerCase();

    for (int i = 0; i < table.getRowCount(); i++) {

        String kode   = table.getValueAt(i, 0).toString().toLowerCase();
        String kategori = table.getValueAt(i, 1).toString().toLowerCase();
        String nama   = table.getValueAt(i, 2).toString().toLowerCase();
        String ukur   = table.getValueAt(i, 3).toString().toLowerCase();
        String warnaa = table.getValueAt(i, 4).toString().toLowerCase();
        String jumlah = table.getValueAt(i, 5).toString().toLowerCase();

        if (kode.contains(cariData)
                || kategori.contains(cariData)
                || nama.contains(cariData)
                || ukur.contains(cariData)
                || warnaa.contains(cariData)
                || jumlah.contains(cariData)) {

            // Pilih baris di tabel
            table.setRowSelectionInterval(i, i);

            // Tampilkan ke form
            kd_brng.setText(table.getValueAt(i, 0).toString());
            Ktgrbrng.setSelectedItem(table.getValueAt(i, 1).toString());
            n_brng.setText(table.getValueAt(i, 2).toString());
            ukuran.setText(table.getValueAt(i, 3).toString());
            warna.setText(table.getValueAt(i, 4).toString());
            Jmlh.setText(table.getValueAt(i, 5).toString());

            // Kunci field yang tidak boleh diedit
            kd_brng.setEditable(false);
            Jmlh.setEditable(false);

            // Nama barang hanya boleh diedit kalau belum pernah transaksi
            n_brng.setEditable(bolehEditNamaBarang());

            JOptionPane.showMessageDialog(null, "Data ditemukan");
            return;
        }
    }

    JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
    }//GEN-LAST:event_mencariActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
       mencariActionPerformed(evt);
    }//GEN-LAST:event_cariActionPerformed

    private void RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETActionPerformed
     
     kosong();          
    kodeOtomatis();    

    cari.setText("");
    table.clearSelection();

   
    n_brng.setEditable(true);

   
    kd_brng.setEditable(false);
    Jmlh.setEditable(false);
    }//GEN-LAST:event_RESETActionPerformed

    private void JmlhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmlhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JmlhActionPerformed

    private void KtgrbrngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KtgrbrngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KtgrbrngActionPerformed
                  
    
    
    
    
    











    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jmlh;
    private javax.swing.JComboBox<String> Ktgrbrng;
    private javax.swing.JButton RESET;
    private javax.swing.JTextField cari;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kd_brng;
    private javax.swing.JButton mencari;
    private javax.swing.JTextField n_brng;
    private javax.swing.JButton simpan;
    private javax.swing.JTable table;
    private javax.swing.JButton ubah;
    private javax.swing.JTextField ukuran;
    private javax.swing.JTextField warna;
    // End of variables declaration//GEN-END:variables
}
