package Menuutama;


import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.swing.JRViewer;




public class menu_utama extends javax.swing.JFrame {

    /**
     * Creates new form menu_utama
     */
    public menu_utama() {
    initComponents();
    this.setExtendedState(JFrame.MAXIMIZED_BOTH);

    // ✅ Ganti pn_navbar biasa dengan GradientPanel
    // Warna: Orange terang → Orange gelap (kiri ke kanan)
    GradientPanel gradientNavbar = new GradientPanel(
        new Color(184, 100, 0),   // start - orange kecoklatan
        new Color(255, 215, 0),   // end   - gold standar
        true                      // true = horizontal
    );
    gradientNavbar.setPreferredSize(pn_navbar.getPreferredSize());
    gradientNavbar.setLayout(new FlowLayout(FlowLayout.LEFT, 20, 15));
    
    // Garis bawah navbar
    gradientNavbar.setBorder(
        javax.swing.BorderFactory.createMatteBorder(
            0, 0, 4, 0,
            new java.awt.Color(180, 60, 0)
        )
    );

    // Pindahkan lb_logo ke gradientNavbar
    pn_navbar.remove(lb_logo);
    gradientNavbar.add(lb_logo);

    // Judul
    JLabel judul = new JLabel("TOKO BUTIK MADE TIRAMI");
    judul.setFont(new Font("Segoe UI", Font.BOLD, 24));
    judul.setForeground(Color.WHITE);
    gradientNavbar.add(judul);

    // Ganti pn_navbar di content pane
    getContentPane().remove(pn_navbar);
    getContentPane().add(gradientNavbar, BorderLayout.PAGE_START);
    
    revalidate();
    repaint();
    
    execute();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_navbar = new javax.swing.JPanel();
        lb_logo = new javax.swing.JLabel();
        pn_sidebar = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pn_menu = new javax.swing.JPanel();
        pn_content = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_navbar.setBackground(new java.awt.Color(255, 204, 153));
        pn_navbar.setPreferredSize(new java.awt.Dimension(872, 300));

        lb_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logo butik.png"))); // NOI18N

        javax.swing.GroupLayout pn_navbarLayout = new javax.swing.GroupLayout(pn_navbar);
        pn_navbar.setLayout(pn_navbarLayout);
        pn_navbarLayout.setHorizontalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_navbarLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lb_logo)
                .addContainerGap(894, Short.MAX_VALUE))
        );
        pn_navbarLayout.setVerticalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_navbarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lb_logo)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(pn_navbar, java.awt.BorderLayout.PAGE_START);

        pn_sidebar.setBackground(new java.awt.Color(255, 255, 255));
        pn_sidebar.setPreferredSize(new java.awt.Dimension(350, 495));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);

        pn_menu.setBackground(new java.awt.Color(255, 255, 255));
        pn_menu.setPreferredSize(new java.awt.Dimension(350, 495));
        pn_menu.setLayout(new javax.swing.BoxLayout(pn_menu, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(pn_menu);

        javax.swing.GroupLayout pn_sidebarLayout = new javax.swing.GroupLayout(pn_sidebar);
        pn_sidebar.setLayout(pn_sidebarLayout);
        pn_sidebarLayout.setHorizontalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        pn_sidebarLayout.setVerticalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );

        getContentPane().add(pn_sidebar, java.awt.BorderLayout.LINE_START);

        pn_content.setBackground(new java.awt.Color(255, 255, 255));
        pn_content.setPreferredSize(new java.awt.Dimension(556, 556));

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));
        pn_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pn_contentLayout = new javax.swing.GroupLayout(pn_content);
        pn_content.setLayout(pn_contentLayout);
        pn_contentLayout.setHorizontalGroup(
            pn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
        );
        pn_contentLayout.setVerticalGroup(
            pn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(pn_content, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1206, 901));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_logo;
    private javax.swing.JPanel pn_content;
    private javax.swing.JPanel pn_menu;
    private javax.swing.JPanel pn_navbar;
    private javax.swing.JPanel pn_sidebar;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables

    private void execute() {
        System.setProperty("net.sf.jasperreports.awt.ignore.missing.font", "true");
        ImageIcon iconMaster = new ImageIcon(getClass().getResource("/IMG/icon master data.png"));
        ImageIcon iconTransaksi = new ImageIcon(getClass().getResource("/IMG/icon transaksi.png"));
        ImageIcon iconReport = new ImageIcon(getClass().getResource("/IMG/icon laporan.png"));
        
        ImageIcon iconDatBar = new ImageIcon(getClass().getResource("/IMG/icon DatBar.png"));
        ImageIcon iconKatBar = new ImageIcon(getClass().getResource("/IMG/icon KatBar.png"));
        ImageIcon iconDatPtgs = new ImageIcon(getClass().getResource("/IMG/icon DatPtgs.png"));
        ImageIcon iconJnsTrans = new ImageIcon(getClass().getResource("/IMG/icon JnsTrans.png"));
        
        ImageIcon iconbarangmasuk = new ImageIcon(getClass().getResource("/IMG/icon barangmasuk.png"));
        ImageIcon iconbarangkeluar = new ImageIcon(getClass().getResource("/IMG/icon barangkeluar.png"));
        ImageIcon iconpembelian = new ImageIcon(getClass().getResource("/IMG/icon transaksi.png"));
        
        // === MASTER DATA ===
        menuItem masDatBar = new menuItem(null, true, iconDatBar, "Data Barang", e -> {
            try {
                masterdata.data_barang form = new masterdata.data_barang();
                java.awt.Container cp = form.getContentPane();
                javax.swing.JPanel isiForm = (javax.swing.JPanel) cp.getComponent(0);
                cp.remove(isiForm);
                tampilkanPanel(isiForm);
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        });

        menuItem masKatBar = new menuItem(null, true, iconKatBar, "Data Supplier", e -> {
            try {
                masterdata.data_supplier form = new masterdata.data_supplier();
                java.awt.Container cp = form.getContentPane();
                javax.swing.JPanel isiForm = (javax.swing.JPanel) cp.getComponent(0);
                cp.remove(isiForm);
                tampilkanPanel(isiForm);
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        });

        menuItem masDatPtgs = new menuItem(null, true, iconDatPtgs, "Data Karyawan", e -> {
            try {
                masterdata.data_karyawan form = new masterdata.data_karyawan();
                java.awt.Container cp = form.getContentPane();
                javax.swing.JPanel isiForm = (javax.swing.JPanel) cp.getComponent(0);
                cp.remove(isiForm);
                tampilkanPanel(isiForm);
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        });

        menuItem masJnsTrans = new menuItem(null, true, iconJnsTrans, "Data Pembeli", e -> {
            try {
                masterdata.data_pembeli form = new masterdata.data_pembeli();
                javax.swing.JPanel wrapper = new javax.swing.JPanel(new java.awt.BorderLayout());
                java.awt.Container cp = form.getContentPane();
                java.awt.Component[] components = cp.getComponents();
                for (java.awt.Component comp : components) {
                    cp.remove(comp);
                    wrapper.add(comp);
                }
                tampilkanPanel(wrapper);
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        });
        
        // === TRANSAKSI ===
        menuItem transBarMasuk = new menuItem(null, true, iconbarangmasuk, "Transaksi Barang Masuk", e -> {
            try {
                Transaksi.ts_barang_masuk form = new Transaksi.ts_barang_masuk();
                java.awt.Container cp = form.getContentPane();
                javax.swing.JPanel isiForm = (javax.swing.JPanel) cp.getComponent(0);
                cp.remove(isiForm);
                tampilkanPanel(isiForm);
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        });

        menuItem transBarKeluar = new menuItem(null, true, iconbarangkeluar, "Transaksi Barang Keluar", e -> {
            try {
                Transaksi.ts_barang_keluar form = new Transaksi.ts_barang_keluar();
                java.awt.Container cp = form.getContentPane();
                javax.swing.JPanel isiForm = (javax.swing.JPanel) cp.getComponent(0);
                cp.remove(isiForm);
                tampilkanPanel(isiForm);
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        });

        // === LAPORAN ===
menuItem lapSupplier = new menuItem(
    null,
    true,
    iconReport,
    "Laporan Supplier",
    e -> {
        try {

            java.sql.Connection conn =
                    koneksisemua.koneksi.getConnection();

            java.io.InputStream report =
                    getClass().getResourceAsStream(
                            "/laporan/laporan_supplier.jasper");

            JasperPrint jp =
                    JasperFillManager.fillReport(
                            report,
                            null,
                            conn);

            JRViewer viewer =
                    new JRViewer(jp);

            pn_utama.removeAll();
            pn_utama.setLayout(new java.awt.BorderLayout());
            pn_utama.add(viewer, java.awt.BorderLayout.CENTER);

            pn_utama.revalidate();
            pn_utama.repaint();

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(
                    null,
                    "Error : " + ex.getMessage());
        }
    }
);

menuItem lapBarangMasukKeluar = new menuItem(
    null,
    true,
    iconReport,
    "Laporan Barang Masuk/Keluar",
    e -> {
        try {

            java.sql.Connection conn =
                    koneksisemua.koneksi.getConnection();

            java.io.InputStream report =
                    getClass().getResourceAsStream(
                            "/laporan/laporan_barang_masuk_keluar.jasper");

            net.sf.jasperreports.engine.JasperPrint jp =
                    net.sf.jasperreports.engine.JasperFillManager.fillReport(
                            report,
                            null,
                            conn);

            net.sf.jasperreports.swing.JRViewer viewer =
                    new net.sf.jasperreports.swing.JRViewer(jp);

            pn_utama.removeAll();
            pn_utama.setLayout(new java.awt.BorderLayout());
            pn_utama.add(viewer, java.awt.BorderLayout.CENTER);

            pn_utama.revalidate();
            pn_utama.repaint();

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(
                    null,
                    "Error : " + ex.getMessage());
        }
    }
);

menuItem lapStok = new menuItem(
    null,
    true,
    iconReport,
    "Laporan Stok Barang",
    e -> {
        try {

            java.sql.Connection conn =
                    koneksisemua.koneksi.getConnection();

            java.io.InputStream report =
                    getClass().getResourceAsStream(
                            "/laporan/stokbarang.jasper");

            JasperPrint jp =
                    JasperFillManager.fillReport(
                            report,
                            null,
                            conn);

            JRViewer viewer =
                    new JRViewer(jp);

            pn_utama.removeAll();
            pn_utama.setLayout(new java.awt.BorderLayout());
            pn_utama.add(viewer, java.awt.BorderLayout.CENTER);

            pn_utama.revalidate();
            pn_utama.repaint();

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(
                    null,
                    ex.getMessage());
        }
    }
);

menuItem lapKaryawan = new menuItem(
    null,
    true,
    iconReport,
    "Laporan Karyawan",
    e -> {
        try {

            java.sql.Connection conn =
                    koneksisemua.koneksi.getConnection();

            java.io.InputStream report =
                    getClass().getResourceAsStream(
                            "/laporan/laporan_Karyawan.jasper");

            JasperPrint jp =
                    JasperFillManager.fillReport(
                            report,
                            null,
                            conn);

            JRViewer viewer =
                    new JRViewer(jp);

            pn_utama.removeAll();
            pn_utama.setLayout(new java.awt.BorderLayout());
            pn_utama.add(viewer, java.awt.BorderLayout.CENTER);

            pn_utama.revalidate();
            pn_utama.repaint();

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(
                    null,
                    "Error : " + ex.getMessage());
        }
    }
);



// === MENU UTAMA ===
        menuItem menuMaster = new menuItem(iconMaster, false, null, "Master Data", null, masDatBar, masKatBar, masDatPtgs, masJnsTrans);
        menuItem menuTransaksi = new menuItem(iconTransaksi, false, null, "Transaksi", null, transBarMasuk, transBarKeluar);
        menuItem menuReport = new menuItem(iconReport,false,null,"Report",null,lapSupplier,lapBarangMasukKeluar,lapStok,lapKaryawan);

        addMenu(menuMaster, menuTransaksi, menuReport);
    }

    public void tampilkanPanel(javax.swing.JPanel panel) {
        pn_utama.removeAll();
        javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(panel);
        scroll.setBorder(null);
        scroll.getVerticalScrollBar().setUnitIncrement(16);
        scroll.getHorizontalScrollBar().setUnitIncrement(16);
        pn_utama.add(scroll, java.awt.BorderLayout.CENTER);
        pn_utama.revalidate();
        pn_utama.repaint();
    }
    
    public void tampilkanTabel(java.sql.ResultSet rs, String judul) {
    try {
        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.BorderLayout(0, 10));
        panel.setBackground(java.awt.Color.WHITE);
        panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));

        // Judul
        javax.swing.JLabel lblJudul = new javax.swing.JLabel(judul, javax.swing.SwingConstants.CENTER);
        lblJudul.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
        panel.add(lblJudul, java.awt.BorderLayout.NORTH);

        // Buat tabel dari ResultSet
        java.sql.ResultSetMetaData meta = rs.getMetaData();
        int kolom = meta.getColumnCount();
        String[] namaKolom = new String[kolom];
        for (int i = 1; i <= kolom; i++) {
            namaKolom[i - 1] = meta.getColumnLabel(i).toUpperCase();
        }
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(namaKolom, 0);
        while (rs.next()) {
            Object[] baris = new Object[kolom];
            for (int i = 1; i <= kolom; i++) {
                baris[i - 1] = rs.getObject(i);
            }
            model.addRow(baris);
        }

        javax.swing.JTable tabel = new javax.swing.JTable(model);
        tabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        tabel.setRowHeight(25);
        tabel.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        tabel.getTableHeader().setBackground(new java.awt.Color(46, 64, 87));
        tabel.getTableHeader().setForeground(java.awt.Color.WHITE);
        tabel.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);

        javax.swing.JScrollPane scrollTabel = new javax.swing.JScrollPane(tabel);
        panel.add(scrollTabel, java.awt.BorderLayout.CENTER);

        tampilkanPanel(panel);
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(null, "Error tabel: " + ex.getMessage());
    }
}

    public void kembaliKeHome() {
        pn_utama.removeAll();
        pn_utama.revalidate();
        pn_utama.repaint();
    }

    private void addMenu(menuItem... menu) {
        for (int i = 0; i < menu.length; i++) {
            pn_menu.add(menu[i]);
            ArrayList<menuItem> subMenu = menu[i].getSubMenu();
            for (menuItem m : subMenu) {
                addMenu(m);
            }
        }
        pn_menu.revalidate();
    }
}